import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { runAiDockerize } from "../agent/dockerize-ai.js";
import { detectProject } from "../detect/project.js";
import { generateDockerFiles } from "../generators/docker.js";
import { dockerSafeTag } from "../util/image-tag.js";

export function repoBaseName(repository: string): string {
  let s = repository.trim().replace(/\.git$/i, "");
  if (s.startsWith("git@") && s.includes(":")) {
    s = s.split(":").pop() ?? s;
  } else {
    const withScheme = /^https?:\/\//i.test(s) ? s : `https://${s}`;
    try {
      s = new URL(withScheme).pathname;
    } catch {
      /* keep s as-is (e.g. org/repo) */
    }
  }
  const base = s.split("/").filter(Boolean).pop() ?? "project";
  return base.replace(/[^a-zA-Z0-9._-]/g, "-") || "project";
}

/** hostPort:containerPort for `docker run -p` */
function runPortPair(projectType: string): { hostPort: number; containerPort: number } {
  if (projectType === "Vite project") return { hostPort: 3000, containerPort: 80 };
  if (projectType === "Streamlit project") return { hostPort: 8501, containerPort: 8501 };
  return { hostPort: 3000, containerPort: 3000 };
}

function buildImage(dest: string, tag: string): { ok: boolean; output: string } {
  return buildImageWithArgs(dest, tag);
}

function buildImageWithArgs(
  dest: string,
  tag: string,
  buildArgs?: Record<string, string>
): { ok: boolean; output: string } {
  const args = ["build", "-t", tag];
  if (buildArgs) {
    for (const [k, v] of Object.entries(buildArgs)) {
      args.push("--build-arg", `${k}=${v}`);
    }
  }
  args.push(".");
  const result = spawnSync("docker", args, {
    cwd: dest,
    encoding: "utf-8",
    maxBuffer: 20 * 1024 * 1024,
  });
  const output = `${result.stdout || ""}${result.stderr || ""}`;
  process.stdout.write(output);
  return { ok: result.status === 0, output };
}

function writeNextDevFallbackDockerfile(dest: string) {
  const dockerfile = `FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
`;
  fs.writeFileSync(path.join(dest, "Dockerfile"), dockerfile);
  console.log("Applied Next.js fallback Dockerfile (dev mode) due build-time env requirements.");
}

function readEnvFile(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  const out: Record<string, string> = {};
  const raw = fs.readFileSync(filePath, "utf-8");
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) out[key] = value;
  }
  return out;
}

function isUsefulValue(v: string | undefined): v is string {
  if (!v) return false;
  const t = v.trim();
  if (!t) return false;
  const bad = ["pk_test_dockfix_placeholder", "sk_test_dockfix_placeholder", "changeme", "your_"];
  return !bad.some((b) => t.toLowerCase().includes(b));
}

function collectNextBuildArgs(dest: string): Record<string, string> {
  const merged: Record<string, string> = {};
  for (const name of [".env", ".env.local", ".env.production", ".env.example"]) {
    Object.assign(merged, readEnvFile(path.join(dest, name)));
  }
  if (isUsefulValue(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)) {
    merged.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  }
  if (isUsefulValue(process.env.CLERK_SECRET_KEY)) {
    merged.CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY;
  }
  const out: Record<string, string> = {};
  if (isUsefulValue(merged.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)) {
    out.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = merged.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  }
  if (isUsefulValue(merged.CLERK_SECRET_KEY)) {
    out.CLERK_SECRET_KEY = merged.CLERK_SECRET_KEY;
  }
  return out;
}

function writeSafeEnvLocal(dest: string, vals: Record<string, string>) {
  const lines = ["# Generated by dockfix --allow-file-fixes (safe config-only edit)"];
  for (const [k, v] of Object.entries(vals)) {
    lines.push(`${k}=${v}`);
  }
  fs.writeFileSync(path.join(dest, ".env.local"), `${lines.join("\n")}\n`);
  console.log("Wrote .env.local with discovered build-time keys.");
}

export type CloneWorkflowOpts = {
  parent: string;
  fullHistory: boolean;
  skipBuild: boolean;
  skipRun: boolean;
  useAi?: boolean;
  aiMaxAttempts?: number;
  allowFileFixes?: boolean;
};

export async function runCloneWorkflow(
  repository: string,
  folderArg: string | undefined,
  opts: CloneWorkflowOpts
) {
  const folder = (folderArg?.trim() || repoBaseName(repository)).replace(/[/\\]/g, "-");
  const dest = path.resolve(opts.parent, folder);

  fs.mkdirSync(opts.parent, { recursive: true });
  if (fs.existsSync(dest)) {
    console.log(`Destination exists: ${dest}`);
    const isGitRepo = spawnSync("git", ["rev-parse", "--is-inside-work-tree"], {
      cwd: dest,
      encoding: "utf-8",
    });
    if (isGitRepo.status !== 0) {
      console.error(`Existing directory is not a git repository: ${dest}`);
      process.exit(1);
    }

    console.log("Pulling latest from origin/main...");
    const pullMain = spawnSync("git", ["pull", "origin", "main"], { cwd: dest, stdio: "inherit" });
    if (pullMain.status !== 0) {
      console.log("Pull from origin/main failed; trying origin/master...");
      const pullMaster = spawnSync("git", ["pull", "origin", "master"], { cwd: dest, stdio: "inherit" });
      if (pullMaster.status !== 0) {
        process.exit(pullMaster.status ?? 1);
      }
    }
  } else {
    const cloneArgs = opts.fullHistory
      ? ["clone", repository, dest]
      : ["clone", "--depth", "1", repository, dest];

    console.log(`Cloning into ${dest}...`);
    const gitResult = spawnSync("git", cloneArgs, { stdio: "inherit" });
    if (gitResult.status !== 0) {
      process.exit(gitResult.status ?? 1);
    }
  }

  console.log(`Scanning ${dest}...`);
  const result = detectProject(dest);
  console.log(`Detected: ${result}`);

  if (opts.useAi) {
    if (result === "Unsupported project") {
      console.log("AI dockerize skipped (unsupported project type).");
      return;
    }
    const tag = `dockfix-${dockerSafeTag(folder)}`;
    await runAiDockerize({
      projectDir: dest,
      imageTag: tag,
      maxAttempts: Math.max(1, opts.aiMaxAttempts ?? 6),
      allowFileFixes: Boolean(opts.allowFileFixes),
    });
    return;
  }

  generateDockerFiles(dest, result);

  if (opts.skipBuild || result === "Unsupported project") {
    if (result === "Unsupported project") {
      console.log("Skipping Docker build (unsupported project type).");
    }
    return;
  }

  const tag = `dockfix-${dockerSafeTag(folder)}`;
  console.log(`Building image ${tag}...`);
  let buildArgs: Record<string, string> | undefined;
  if (opts.allowFileFixes && result === "Next.js project") {
    const discovered = collectNextBuildArgs(dest);
    if (Object.keys(discovered).length > 0) {
      writeSafeEnvLocal(dest, discovered);
      buildArgs = discovered;
    }
  }
  let build = buildImageWithArgs(dest, tag, buildArgs);

  if (!build.ok && result === "Next.js project") {
    const lower = build.output.toLowerCase();
    const hasClerkOrKeyIssue =
      lower.includes("missing publishablekey") ||
      lower.includes("publishablekey passed to clerk is invalid") ||
      (lower.includes("clerk") && lower.includes("publishablekey"));
    if (hasClerkOrKeyIssue) {
      writeNextDevFallbackDockerfile(dest);
      console.log(`Rebuilding image ${tag} with fallback Dockerfile...`);
      build = buildImage(dest, tag);
    }
  }

  if (!build.ok) {
    process.exit(1);
  }

  if (opts.skipRun) {
    const { hostPort, containerPort } = runPortPair(result);
    console.log(`Image built. Example run:`);
    console.log(`  cd ${dest}`);
    console.log(`  docker run --rm -it -p ${hostPort}:${containerPort} ${tag}`);
    return;
  }

  const { hostPort, containerPort } = runPortPair(result);
  console.log(`Running at http://127.0.0.1:${hostPort} (container ${containerPort}) — Ctrl+C to stop.`);
  const runResult = spawnSync(
    "docker",
    ["run", "--rm", "-it", "-p", `${hostPort}:${containerPort}`, tag],
    { cwd: dest, stdio: "inherit" }
  );
  if (runResult.status !== 0) {
    process.exit(runResult.status ?? 1);
  }
}
